name: Hello
on:
  workflow_call:
    inputs:
      pkgbuild_dir:
        description: "test input"
        required: true
        type: string
      extra_pacman_packages:
        description: "test optional"
        required: false
        type: string
        default: ""
    secrets:
      REPO_ARCH_TOKEN:
        description: "test secret"
        required: true
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "pkgbuild_dir: ${{ inputs.pkgbuild_dir }}"
          echo "extra: ${{ inputs.extra_pacman_packages }}"
          echo "token length: ${#REPO_ARCH_TOKEN}"
        env:
          REPO_ARCH_TOKEN: ${{ secrets.REPO_ARCH_TOKEN }}
