name: Publish Arch package Rust
on:
  workflow_call:
    inputs:
      pkgbuild_dir:
        required: true
        type: string
      extra_pacman_packages:
        required: false
        type: string
        default: ""
    secrets:
      REPO_ARCH_TOKEN:
        required: true
env:
  REPO_NAME: repo-arch
  REPO_OWNER: mythofmeat
  CARGO_TARGET_DIR_HOST: /home/builder/cargo-target
  CARGO_HOME_HOST: /home/builder/.cargo
jobs:
  package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - run: echo ok
