name: Publish Arch package Rust
on:
  workflow_call:
    inputs:
      pkgbuild_dir:
        required: true
        type: string
      extra_pacman_packages:
        required: false
        type: string
        default: ""
    secrets:
      REPO_ARCH_TOKEN:
        required: true
jobs:
  package:
    runs-on: ubuntu-latest
    env:
      PACMAN_KEY: pacman-${{ hashFiles('.github/workflows/package.yml') }}
    steps:
      - run: echo "${{ env.PACMAN_KEY }}"
